2022-08-01T16:22:06.549265+00:00 heroku[router]: at=info method=POST path="/start" host=battlesnake-summer.herokuapp.com request_id=aed32e20-5458-4601-ba29-30a05a86b681 fwd="143.198.42.44" dyno=web.1 connect=0ms service=2ms status=200 bytes=223 protocol=https
2022-08-01T16:22:06.913348+00:00 heroku[router]: at=info method=POST path="/move" host=battlesnake-summer.herokuapp.com request_id=ed0ea127-d781-4a74-975a-e0568c8d60ca fwd="143.198.42.44" dyno=web.1 connect=0ms service=7ms status=500 bytes=16436 protocol=https
2022-08-01T16:22:06.677275+00:00 heroku[router]: at=info method=POST path="/move" host=battlesnake-summer.herokuapp.com request_id=4baba057-d34a-4c2a-a0e9-97475e1c0d61 fwd="143.198.42.44" dyno=web.1 connect=1ms service=9ms status=500 bytes=16436 protocol=https
2022-08-01T16:22:06.547407+00:00 app[web.1]: 17fa6add-2cea-40f6-a6ca-efaea8d7dc51 START
2022-08-01T16:22:06.675210+00:00 app[web.1]: Traceback (most recent call last):
2022-08-01T16:22:06.675217+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
2022-08-01T16:22:06.675218+00:00 app[web.1]: return self.wsgi_app(environ, start_response)
2022-08-01T16:22:06.675219+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
2022-08-01T16:22:06.675219+00:00 app[web.1]: response = self.handle_exception(e)
2022-08-01T16:22:06.675219+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
2022-08-01T16:22:06.675220+00:00 app[web.1]: response = self.full_dispatch_request()
2022-08-01T16:22:06.675220+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
2022-08-01T16:22:06.675221+00:00 app[web.1]: rv = self.handle_user_exception(e)
2022-08-01T16:22:06.675221+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
2022-08-01T16:22:06.675221+00:00 app[web.1]: rv = self.dispatch_request()
2022-08-01T16:22:06.675221+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
2022-08-01T16:22:06.675222+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-08-01T16:22:06.675222+00:00 app[web.1]: File "/app/src/main.py", line 45, in handle_move
2022-08-01T16:22:06.675222+00:00 app[web.1]: move = logic.choose_move(data)
2022-08-01T16:22:06.675222+00:00 app[web.1]: File "/app/src/logic.py", line 136, in choose_move
2022-08-01T16:22:06.675222+00:00 app[web.1]: Grid = grid(board['height'], data)
2022-08-01T16:22:06.675223+00:00 app[web.1]: File "/app/src/grid.py", line 83, in __init__
2022-08-01T16:22:06.675223+00:00 app[web.1]: self.grid[head['y']][head['x']].thisIsObstacle()
2022-08-01T16:22:06.675223+00:00 app[web.1]: AttributeError: 'gridCell' object has no attribute 'thisIsObstacle'
2022-08-01T16:22:07.183601+00:00 heroku[router]: at=info method=POST path="/move" host=battlesnake-summer.herokuapp.com request_id=f29d83f7-cc30-4977-b302-b52c0fd64c4c fwd="143.198.42.44" dyno=web.1 connect=0ms service=6ms status=500 bytes=16436 protocol=https
2022-08-01T16:22:06.911845+00:00 app[web.1]: Traceback (most recent call last):
2022-08-01T16:22:06.911851+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
2022-08-01T16:22:06.911852+00:00 app[web.1]: return self.wsgi_app(environ, start_response)
2022-08-01T16:22:06.911852+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
2022-08-01T16:22:06.911853+00:00 app[web.1]: response = self.handle_exception(e)
2022-08-01T16:22:06.911853+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
2022-08-01T16:22:06.911854+00:00 app[web.1]: response = self.full_dispatch_request()
2022-08-01T16:22:06.911855+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
2022-08-01T16:22:06.911855+00:00 app[web.1]: rv = self.handle_user_exception(e)
2022-08-01T16:22:06.911856+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
2022-08-01T16:22:06.911856+00:00 app[web.1]: rv = self.dispatch_request()
2022-08-01T16:22:06.911857+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
2022-08-01T16:22:06.911857+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-08-01T16:22:06.911858+00:00 app[web.1]: File "/app/src/main.py", line 45, in handle_move
2022-08-01T16:22:06.911858+00:00 app[web.1]: move = logic.choose_move(data)
2022-08-01T16:22:06.911858+00:00 app[web.1]: File "/app/src/logic.py", line 136, in choose_move
2022-08-01T16:22:06.911859+00:00 app[web.1]: Grid = grid(board['height'], data)
2022-08-01T16:22:06.911859+00:00 app[web.1]: File "/app/src/grid.py", line 83, in __init__
2022-08-01T16:22:06.911859+00:00 app[web.1]: self.grid[head['y']][head['x']].thisIsObstacle()
2022-08-01T16:22:06.911860+00:00 app[web.1]: AttributeError: 'gridCell' object has no attribute 'thisIsObstacle'
2022-08-01T16:22:07.182029+00:00 app[web.1]: Traceback (most recent call last):
2022-08-01T16:22:07.182037+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
2022-08-01T16:22:07.182038+00:00 app[web.1]: return self.wsgi_app(environ, start_response)
2022-08-01T16:22:07.182038+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
2022-08-01T16:22:07.182039+00:00 app[web.1]: response = self.handle_exception(e)
2022-08-01T16:22:07.182039+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
2022-08-01T16:22:07.182039+00:00 app[web.1]: response = self.full_dispatch_request()
2022-08-01T16:22:07.182040+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
2022-08-01T16:22:07.182040+00:00 app[web.1]: rv = self.handle_user_exception(e)
2022-08-01T16:22:07.182040+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
2022-08-01T16:22:07.182041+00:00 app[web.1]: rv = self.dispatch_request()
2022-08-01T16:22:07.182041+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
2022-08-01T16:22:07.182041+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-08-01T16:22:07.182041+00:00 app[web.1]: File "/app/src/main.py", line 45, in handle_move
2022-08-01T16:22:07.182042+00:00 app[web.1]: move = logic.choose_move(data)
2022-08-01T16:22:07.182042+00:00 app[web.1]: File "/app/src/logic.py", line 136, in choose_move
2022-08-01T16:22:07.182042+00:00 app[web.1]: Grid = grid(board['height'], data)
2022-08-01T16:22:07.182042+00:00 app[web.1]: File "/app/src/grid.py", line 83, in __init__
2022-08-01T16:22:07.182042+00:00 app[web.1]: self.grid[head['y']][head['x']].thisIsObstacle()
2022-08-01T16:22:07.182043+00:00 app[web.1]: AttributeError: 'gridCell' object has no attribute 'thisIsObstacle'
2022-08-01T16:22:07.504879+00:00 app[web.1]: Traceback (most recent call last):
2022-08-01T16:22:07.504886+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
2022-08-01T16:22:07.504887+00:00 app[web.1]: return self.wsgi_app(environ, start_response)
2022-08-01T16:22:07.504888+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
2022-08-01T16:22:07.504888+00:00 app[web.1]: response = self.handle_exception(e)
2022-08-01T16:22:07.504888+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
2022-08-01T16:22:07.504888+00:00 app[web.1]: response = self.full_dispatch_request()
2022-08-01T16:22:07.504899+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
2022-08-01T16:22:07.504899+00:00 app[web.1]: rv = self.handle_user_exception(e)
2022-08-01T16:22:07.504900+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
2022-08-01T16:22:07.504900+00:00 app[web.1]: rv = self.dispatch_request()
2022-08-01T16:22:07.504900+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
2022-08-01T16:22:07.504900+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-08-01T16:22:07.504901+00:00 app[web.1]: File "/app/src/main.py", line 45, in handle_move
2022-08-01T16:22:07.504901+00:00 app[web.1]: move = logic.choose_move(data)
2022-08-01T16:22:07.504902+00:00 app[web.1]: File "/app/src/logic.py", line 136, in choose_move
2022-08-01T16:22:07.504902+00:00 app[web.1]: Grid = grid(board['height'], data)
2022-08-01T16:22:07.504902+00:00 app[web.1]: File "/app/src/grid.py", line 83, in __init__
2022-08-01T16:22:07.504903+00:00 app[web.1]: self.grid[head['y']][head['x']].thisIsObstacle()
2022-08-01T16:22:07.504903+00:00 app[web.1]: AttributeError: 'gridCell' object has no attribute 'thisIsObstacle'
2022-08-01T16:22:07.506425+00:00 heroku[router]: at=info method=POST path="/move" host=battlesnake-summer.herokuapp.com request_id=6a2dfc7a-e36c-4a48-a88f-649462b1fcb7 fwd="143.198.42.44" dyno=web.1 connect=0ms service=6ms status=500 bytes=16436 protocol=https
2022-08-01T16:22:07.831720+00:00 heroku[router]: at=info method=POST path="/move" host=battlesnake-summer.herokuapp.com request_id=caf36cd0-4fe6-49bb-8d9f-f98e17398de1 fwd="143.198.42.44" dyno=web.1 connect=0ms service=6ms status=500 bytes=16436 protocol=https
2022-08-01T16:22:08.057597+00:00 heroku[router]: at=info method=POST path="/move" host=battlesnake-summer.herokuapp.com request_id=712fd961-bf31-48c7-a151-f2dbdbddca14 fwd="143.198.42.44" dyno=web.1 connect=0ms service=7ms status=500 bytes=16436 protocol=https
2022-08-01T16:22:07.830229+00:00 app[web.1]: Traceback (most recent call last):
2022-08-01T16:22:07.830238+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
2022-08-01T16:22:07.830238+00:00 app[web.1]: return self.wsgi_app(environ, start_response)
2022-08-01T16:22:07.830238+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
2022-08-01T16:22:07.830239+00:00 app[web.1]: response = self.handle_exception(e)
2022-08-01T16:22:07.830239+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
2022-08-01T16:22:07.830239+00:00 app[web.1]: response = self.full_dispatch_request()
2022-08-01T16:22:07.830240+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
2022-08-01T16:22:07.830240+00:00 app[web.1]: rv = self.handle_user_exception(e)
2022-08-01T16:22:07.830240+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
2022-08-01T16:22:07.830240+00:00 app[web.1]: rv = self.dispatch_request()
2022-08-01T16:22:07.830241+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
2022-08-01T16:22:07.830241+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-08-01T16:22:07.830241+00:00 app[web.1]: File "/app/src/main.py", line 45, in handle_move
2022-08-01T16:22:07.830242+00:00 app[web.1]: move = logic.choose_move(data)
2022-08-01T16:22:07.830242+00:00 app[web.1]: File "/app/src/logic.py", line 136, in choose_move
2022-08-01T16:22:07.830242+00:00 app[web.1]: Grid = grid(board['height'], data)
2022-08-01T16:22:07.830242+00:00 app[web.1]: File "/app/src/grid.py", line 83, in __init__
2022-08-01T16:22:07.830242+00:00 app[web.1]: self.grid[head['y']][head['x']].thisIsObstacle()
2022-08-01T16:22:07.830243+00:00 app[web.1]: AttributeError: 'gridCell' object has no attribute 'thisIsObstacle'
2022-08-01T16:22:08.056031+00:00 app[web.1]: Traceback (most recent call last):
2022-08-01T16:22:08.056035+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2091, in __call__
2022-08-01T16:22:08.056035+00:00 app[web.1]: return self.wsgi_app(environ, start_response)
2022-08-01T16:22:08.056035+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2076, in wsgi_app
2022-08-01T16:22:08.056036+00:00 app[web.1]: response = self.handle_exception(e)
2022-08-01T16:22:08.056036+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 2073, in wsgi_app
2022-08-01T16:22:08.056036+00:00 app[web.1]: response = self.full_dispatch_request()
2022-08-01T16:22:08.056037+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1518, in full_dispatch_request
2022-08-01T16:22:08.056037+00:00 app[web.1]: rv = self.handle_user_exception(e)
2022-08-01T16:22:08.056037+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1516, in full_dispatch_request
2022-08-01T16:22:08.056038+00:00 app[web.1]: rv = self.dispatch_request()
2022-08-01T16:22:08.056038+00:00 app[web.1]: File "/app/.heroku/python/lib/python3.9/site-packages/flask/app.py", line 1502, in dispatch_request
2022-08-01T16:22:08.056038+00:00 app[web.1]: return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
2022-08-01T16:22:08.056039+00:00 app[web.1]: File "/app/src/main.py", line 45, in handle_move
2022-08-01T16:22:08.056039+00:00 app[web.1]: move = logic.choose_move(data)
2022-08-01T16:22:08.056039+00:00 app[web.1]: File "/app/src/logic.py", line 136, in choose_move
2022-08-01T16:22:08.056039+00:00 app[web.1]: Grid = grid(board['height'], data)
2022-08-01T16:22:08.056039+00:00 app[web.1]: File "/app/src/grid.py", line 83, in __init__
2022-08-01T16:22:08.056039+00:00 app[web.1]: self.grid[head['y']][head['x']].thisIsObstacle()
2022-08-01T16:22:08.056040+00:00 app[web.1]: AttributeError: 'gridCell' object has no attribute 'thisIsObstacle'
2022-08-01T16:22:08.320107+00:00 app[web.1]: 17fa6add-2cea-40f6-a6ca-efaea8d7dc51 END
2022-08-01T16:22:08.321750+00:00 heroku[router]: at=info method=POST path="/end" host=battlesnake-summer.herokuapp.com request_id=418d412f-dac4-4f99-b21d-f1d44a58d259 fwd="143.198.42.44" dyno=web.1 connect=0ms service=2ms status=200 bytes=223 protocol=https
2022-08-01T16:21:23.000000+00:00 app[api]: Build started by user abdelmoniemmmh@gmail.com
